// <auto-generated />
namespace BtcProApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Register_addfield_isblocked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Register_addfield_isblocked));
        
        string IMigrationMetadata.Id
        {
            get { return "201706260832115_Register_addfield_isblocked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
