// <auto-generated />
namespace BtcProApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Register_WorkingLeg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Register_WorkingLeg));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131843528_Register_WorkingLeg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
